language: java
before_install:
- curl https://raw.github.com/liveSense/all/master/travis-settings.xml --create-dirs
  -o target/travis/settings.xml
jdk:
- openjdk6
script:
- mvn deploy --settings target/travis/settings.xml
env:
  global:
  - secure: kGb3QvWdnzo+vw7qEmeiE50hBp9UwAkove1/LwgmPWAszDOL2+5jAQTV1vrXNyNFSHWe1irfmFNrk8j0UUTNGwA4G4fe5OG96yx/oj288E7yv2pet25EcyHE8OaCP5GqCT9Laz+XtTq06Wj5tUbp7Q3NPb0m1dUkxH/bxOPB+FE=
  - secure: AT4YaeoNSbzgCYT1Gu+j/ESAilN2YzszaJcbTFAmAIolaDWIggez/QYm3s3QWRAbXjo2R7PvcsYyTAx+1X+naLYRXMnCP0UG0LKdlOxB0SahBara2AQo3t2p9nLynWo52ByiBJfNR32BRdK9H4V1ktv8xHDlu+g0OLmvmVKi43s=
